server:
  http_port: 8080

grpc_recognisers:
  # The keys in this object will become recognition api query parameters.
  # i.e. to use this recogniser, do http://localhost:8080/entities?recogniser=dictionary
  swissprot-genes-proteins:
    host: dictionary
    port: 50051

blacklist: '/app/config/blacklist.yml'





